### ISSUE TITLE
Changes to the ESP8266 SDK now enforce ISRs to be in IRAM

### ISSUE THREAD

**Issue by vloschiavo** [trlafleur/Acurite-00592TX-Decoder-ESP32a#1]
After compiling for and pushing the code to an ESP8266, wifi connects, then the ESP8266, throws an error: "ISR not in IRAM", core dumps, and reboots.

I've found that the SDK is now enforcing the requirement for ISRs to now be in IRAM.  

Issue previously reported: https://github.com/esp8266/Arduino/issues/6127

Per the documentation here: https://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html?highlight=isr%20icache_RAM_attr#other-causes-for-crashes

This is a simple fix:
On line 611 of Acurite_00592TX_Decoder_ESP32a.ino
**change**: "void interrupt_handler()"
**to**: "void ICACHE_RAM_ATTR interrupt_handler()"

**Comment by trlafleur** [comment]
Thanks.   

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~



On Sep 18, 2020, at 5:52 PM, Vince Loschiavo <notifications@github.com> wrote:

﻿
After compiling for and pushing the code to an ESP8266, wifi connects, then the ESP8266, throws an error: "ISR not in IRAM", core dumps, and reboots.

I've found that the SDK is now enforcing the requirement for ISRs to now be in IRAM.

Issue previously reported: esp8266/Arduino#6127

Per the documentation here: https://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html?highlight=isr%20icache_RAM_attr#other-causes-for-crashes

This is a simple fix:
On line 611 of
change: "void interrupt_handler()"
to: "void ICACHE_RAM_ATTR interrupt_handler()"

**Comment by vloschiavo** [comment]
I just send a pull request to fix it.  
BTW, this project is great! It's exactly what I was looking for to solve a problem in my home automation.  Great job!
